services:
  - type: redis
    name: studyflow-redis
    plan: standard
    ipAllowList: []

  - type: web
    name: StudyFlowSuite
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: ROLE
        value: web
      - key: DATABASE_URL
        fromService:
          name: studyflow-db
          type: pserv
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false

  - type: worker
    name: studyflow-celery-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: ROLE
        value: worker
      - key: DATABASE_URL
        fromService:
          name: studyflow-db
          type: pserv
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false

  - type: web
    name: studyflow-flower
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: ROLE
        value: flower
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString
