services:
  - type: web
    name: StudyFlowSuite-1
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    startCommand: "gunicorn StudyFlow.backend.app:app -k gevent --bind 0.0.0.0:10000"
    disk:
      name: data-disk
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: ROLE
        value: web
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: worker
    name: studyflow-celery-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    startCommand: "celery --app StudyFlow.backend.tasks worker --loglevel=info --concurrency=4"
    disk:
      name: data-disk
      mountPath: /mnt/data
      sizeGB: 1
    envVars:
      - key: ROLE
        value: worker
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: web
    name: studyflow-flower
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    startCommand: "celery --app StudyFlow.backend.tasks flower --loglevel=info"
    envVars:
      - key: ROLE
        value: flower
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: redis
    name: studyflow-redis
    plan: standard
    maxmemoryPolicy: noeviction
    ipAllowList: []  # internal only
