services:
  - type: web
    name: studyflow-web
    env: docker
    region: ohio
    plan: standard
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: worker
    name: studyflow-celery-worker
    env: docker
    region: ohio
    plan: standard
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: web
    name: studyflow-flower
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: studyflow-redis
          type: redis
          property: connectionString

  - type: redis
    name: studyflow-redis
    region: ohio
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []  # allow internal connections only
