-- Migration: Switch from OpenAI 1536-dim embeddings to Gemini 768-dim
-- This clears all existing embeddings (they'll be re-generated by Celery task)

-- Step 1: Drop the old index (can't alter vector dimensions with index)
DROP INDEX IF EXISTS note_chunks_embedding_idx;

-- Step 2: Alter the embedding column to 768 dimensions
ALTER TABLE note_chunks
ALTER COLUMN embedding TYPE vector(768)
USING NULL;

-- Step 3: Set all embeddings to NULL (they need re-generation with Gemini)
UPDATE note_chunks SET embedding = NULL;

-- Step 4: Recreate the index for 768-dim vectors
CREATE INDEX IF NOT EXISTS note_chunks_embedding_idx ON note_chunks
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Step 5: Update the search function to use 768-dim vectors
CREATE OR REPLACE FUNCTION search_notes_with_vector(
    query_embedding VECTOR(768),
    search_user_id UUID,
    search_university TEXT DEFAULT NULL,
    search_course_code TEXT DEFAULT NULL,
    match_threshold FLOAT DEFAULT 0.7,
    match_count INT DEFAULT 5
)
RETURNS TABLE (
    id UUID,
    note_id UUID,
    chunk_text TEXT,
    content_summary TEXT,
    similarity FLOAT,
    university TEXT,
    course_code TEXT,
    is_own_note BOOLEAN
)
LANGUAGE plpgsql
AS $$
DECLARE
    searcher_opted_in BOOLEAN;
BEGIN
    SELECT COALESCE(collective_brain_opt_in, TRUE)
    INTO searcher_opted_in
    FROM user_profiles
    WHERE user_profiles.id = search_user_id;

    RETURN QUERY
    SELECT
        nc.id,
        nc.note_id,
        nc.chunk_text,
        nc.content_summary,
        1 - (nc.embedding <=> query_embedding) AS similarity,
        nc.university,
        nc.course_code,
        (nc.user_id = search_user_id) AS is_own_note
    FROM note_chunks nc
    INNER JOIN user_profiles note_owner ON nc.user_id = note_owner.id
    WHERE
        nc.embedding IS NOT NULL
        AND (
            nc.user_id = search_user_id
            OR
            (
                searcher_opted_in = TRUE
                AND COALESCE(note_owner.collective_brain_opt_in, TRUE) = TRUE
                AND nc.is_public = TRUE
            )
        )
        AND 1 - (nc.embedding <=> query_embedding) > match_threshold
    ORDER BY nc.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;
